#!/usr/bin/env fish

source (dirname (status filename))/../utils

argparse --name aiu-clear-cache 'h/help' -- $argv
or exit
handle_help_switch commands/aiu-clear-cache "$_flag_help"

set -l cache_path (get_cache_path)
if test -d "$cache_path"
    set -l cache_file (get_cache_file)
    if test -f "$cache_file"
        rm "$cache_file"
    end
end
